@startuml "Diagrama de Caso de Uso de Categoria"

:Admin: -> (Criar categoria)
:Admin: -> (Atualizar categoria)
:Admin: -> (Excluir categoria)
:Admin: -> (Consultar uma categoria)
:Admin: -> (Consultar categorias)


@enduml